### ISSUE TITLE
How refer to a SKOS ontology?

### ISSUE THREAD

**Issue by nicky508** [fusepoolP3/p3-dictionary-matcher-transformer#7]
I`am playing around with the application. It seems to work well. Earlier (a few months) I tried the example of New York times and it worked. However the uris seems to be death at the moment. I trying to use one of my own SKOS ontologies. But I cannot figuring out how the dictionary matcher it can use. 

In the example I see the there is a redirection towards a descriptors.rdf. The SKOS ontology I want to use does not have such descriptors file. Is this the missing link, should I add this file. And if so, according what specifications? 

**UPDATE**
Found that if I give a uri to a concept, that the matcher finds this specific concept in the text. But I want to give more than only one concept. It seems I cannot refer to a concept-scheme or so. Where should I refer to if I want to use the whole ontology?

**Comment by retog** [comment]
Unfortunately `data.nytimes.com` seems to be down, so the example doesn't work. I've taken an old version of the taxonomy from the way back machine and uploaded it to `fusepoolp3.github.io` so that the following now works: 

    curl -X POST -d "Frauds and Swindlings cause significant concerns with regards to Ethics." "http://sandbox.fusepool.info:8301/?taxonomy=http://fusepoolp3.github.io/nytaxonomy.rdf"

I'm not sure if with this you can find the answer to your question, if so please close the issue otherwise please describe in more detail what you'd like to do.

**Comment by nicky508** [comment]
Thnks for your response, I think this example will help me.
